/* GENERADO AUTOMATICAMENTE por robot-nube.ps1 (API Gescom, GitHub Actions) - NO EDITAR A MANO
   Ultima actualizacion: 2026-10-06 12:51 */
window.__TP_CONFIG__ = { SHEET_CSV_URL: '', umbrales: { bueno: 90, medio: 75 }, diasHistorial: 14 };
window.__TP_DATA__ = { registros: [
 {"fecha":"2026-10-01","fletero":"Alejandro Fabian Maiorano","zona":"","repartos":1,"entregas_asignadas":29,"entregas_realizadas":26,"cartones_a_retornar":33,"cartones_retornados":29}
,{"fecha":"2026-10-01","fletero":"Algañaraz German Marcelo","zona":"","repartos":1,"entregas_asignadas":49,"entregas_realizadas":48,"cartones_a_retornar":34,"cartones_retornados":0}
,{"fecha":"2026-10-01","fletero":"Diego Andrés Martorello","zona":"","repartos":2,"entregas_asignadas":66,"entregas_realizadas":66,"cartones_a_retornar":60,"cartones_retornados":56}
,{"fecha":"2026-10-01","fletero":"Edgardo Jacinto Gomez","zona":"","repartos":1,"entregas_asignadas":42,"entregas_realizadas":39,"cartones_a_retornar":29,"cartones_retornados":29}
,{"fecha":"2026-10-01","fletero":"Emanuel Valentino Cossu","zona":"","repartos":1,"entregas_asignadas":39,"entregas_realizadas":37,"cartones_a_retornar":29,"cartones_retornados":27}
,{"fecha":"2026-10-01","fletero":"Ezequiel Dario Gargan","zona":"","repartos":1,"entregas_asignadas":55,"entregas_realizadas":51,"cartones_a_retornar":34,"cartones_retornados":34}
,{"fecha":"2026-10-01","fletero":"Leandro Martín Cossu","zona":"","repartos":1,"entregas_asignadas":23,"entregas_realizadas":23,"cartones_a_retornar":17,"cartones_retornados":17}
,{"fecha":"2026-10-01","fletero":"Leo Damian Moncada","zona":"","repartos":1,"entregas_asignadas":33,"entregas_realizadas":32,"cartones_a_retornar":36,"cartones_retornados":0}
,{"fecha":"2026-10-01","fletero":"Marcelo Javier Acuña","zona":"","repartos":1,"entregas_asignadas":39,"entregas_realizadas":38,"cartones_a_retornar":36,"cartones_retornados":34}
,{"fecha":"2026-10-01","fletero":"Mario Luis Gastiarena","zona":"","repartos":1,"entregas_asignadas":36,"entregas_realizadas":36,"cartones_a_retornar":42,"cartones_retornados":40}
,{"fecha":"2026-10-01","fletero":"Rodrigo Martin Soto","zona":"","repartos":1,"entregas_asignadas":33,"entregas_realizadas":32,"cartones_a_retornar":40,"cartones_retornados":30}
,{"fecha":"2026-10-02","fletero":"Alejandro Fabian Maiorano","zona":"","repartos":1,"entregas_asignadas":37,"entregas_realizadas":37,"cartones_a_retornar":64,"cartones_retornados":60}
,{"fecha":"2026-10-02","fletero":"Algañaraz German Marcelo","zona":"","repartos":1,"entregas_asignadas":63,"entregas_realizadas":59,"cartones_a_retornar":69,"cartones_retornados":63}
,{"fecha":"2026-10-02","fletero":"Diego Andrés Martorello","zona":"","repartos":1,"entregas_asignadas":70,"entregas_realizadas":67,"cartones_a_retornar":58,"cartones_retornados":50}
,{"fecha":"2026-10-02","fletero":"Edgardo Jacinto Gomez","zona":"","repartos":1,"entregas_asignadas":37,"entregas_realizadas":37,"cartones_a_retornar":52,"cartones_retornados":50}
,{"fecha":"2026-10-02","fletero":"Emanuel Valentino Cossu","zona":"","repartos":1,"entregas_asignadas":62,"entregas_realizadas":59,"cartones_a_retornar":42,"cartones_retornados":40}
,{"fecha":"2026-10-02","fletero":"Enzo Julián Rizzoni","zona":"","repartos":1,"entregas_asignadas":50,"entregas_realizadas":50,"cartones_a_retornar":57,"cartones_retornados":49}
,{"fecha":"2026-10-02","fletero":"Leandro Martín Cossu","zona":"","repartos":1,"entregas_asignadas":49,"entregas_realizadas":46,"cartones_a_retornar":62,"cartones_retornados":60}
,{"fecha":"2026-10-02","fletero":"Leo Damian Moncada","zona":"","repartos":1,"entregas_asignadas":36,"entregas_realizadas":35,"cartones_a_retornar":49,"cartones_retornados":42}
,{"fecha":"2026-10-02","fletero":"Marcelo Javier Acuña","zona":"","repartos":1,"entregas_asignadas":56,"entregas_realizadas":56,"cartones_a_retornar":94,"cartones_retornados":94}
,{"fecha":"2026-10-02","fletero":"Mario Luis Gastiarena","zona":"","repartos":1,"entregas_asignadas":59,"entregas_realizadas":59,"cartones_a_retornar":39,"cartones_retornados":35}
,{"fecha":"2026-10-02","fletero":"Rodrigo Martin Soto","zona":"","repartos":1,"entregas_asignadas":53,"entregas_realizadas":50,"cartones_a_retornar":64,"cartones_retornados":60}
,{"fecha":"2026-10-05","fletero":"Alejandro Fabian Maiorano","zona":"","repartos":1,"entregas_asignadas":49,"entregas_realizadas":49,"cartones_a_retornar":37,"cartones_retornados":0}
,{"fecha":"2026-10-05","fletero":"Algañaraz German Marcelo","zona":"","repartos":1,"entregas_asignadas":35,"entregas_realizadas":35,"cartones_a_retornar":36,"cartones_retornados":0}
,{"fecha":"2026-10-05","fletero":"Diego Andrés Martorello","zona":"","repartos":2,"entregas_asignadas":93,"entregas_realizadas":93,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-05","fletero":"Edgardo Jacinto Gomez","zona":"","repartos":1,"entregas_asignadas":29,"entregas_realizadas":29,"cartones_a_retornar":36,"cartones_retornados":32}
,{"fecha":"2026-10-05","fletero":"Emanuel Valentino Cossu","zona":"","repartos":1,"entregas_asignadas":64,"entregas_realizadas":64,"cartones_a_retornar":40,"cartones_retornados":37}
,{"fecha":"2026-10-05","fletero":"Enzo Julián Rizzoni","zona":"","repartos":1,"entregas_asignadas":52,"entregas_realizadas":52,"cartones_a_retornar":36,"cartones_retornados":32}
,{"fecha":"2026-10-05","fletero":"Leandro Martín Cossu","zona":"","repartos":1,"entregas_asignadas":46,"entregas_realizadas":46,"cartones_a_retornar":38,"cartones_retornados":35}
,{"fecha":"2026-10-05","fletero":"Leo Damian Moncada","zona":"","repartos":1,"entregas_asignadas":48,"entregas_realizadas":48,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-05","fletero":"Marcelo Javier Acuña","zona":"","repartos":1,"entregas_asignadas":24,"entregas_realizadas":24,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-05","fletero":"Mario Luis Gastiarena","zona":"","repartos":1,"entregas_asignadas":52,"entregas_realizadas":52,"cartones_a_retornar":38,"cartones_retornados":34}
,{"fecha":"2026-10-05","fletero":"Rodrigo Martin Soto","zona":"","repartos":1,"entregas_asignadas":45,"entregas_realizadas":45,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Alejandro Fabian Maiorano","zona":"","repartos":1,"entregas_asignadas":47,"entregas_realizadas":47,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Algañaraz German Marcelo","zona":"","repartos":2,"entregas_asignadas":102,"entregas_realizadas":102,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Diego Andrés Martorello","zona":"","repartos":2,"entregas_asignadas":68,"entregas_realizadas":68,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Edgardo Jacinto Gomez","zona":"","repartos":3,"entregas_asignadas":98,"entregas_realizadas":98,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Emanuel Valentino Cossu","zona":"","repartos":2,"entregas_asignadas":61,"entregas_realizadas":61,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Ezequiel Dario Gargan","zona":"","repartos":1,"entregas_asignadas":67,"entregas_realizadas":67,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Leandro Martín Cossu","zona":"","repartos":2,"entregas_asignadas":53,"entregas_realizadas":53,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Leo Damian Moncada","zona":"","repartos":2,"entregas_asignadas":74,"entregas_realizadas":74,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Marcelo Javier Acuña","zona":"","repartos":2,"entregas_asignadas":66,"entregas_realizadas":66,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Mario Luis Gastiarena","zona":"","repartos":1,"entregas_asignadas":66,"entregas_realizadas":66,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-06","fletero":"Rodrigo Martin Soto","zona":"","repartos":1,"entregas_asignadas":38,"entregas_realizadas":38,"cartones_a_retornar":0,"cartones_retornados":0}
] };
window.__TP_DATA__.motivos = [{"motivo":"RECHAZO","cantidad":12},{"motivo":"CERRADO","cantidad":6},{"motivo":"ERROR DE PREVENTA","cantidad":5},{"motivo":"Error de Armado: Diferencia de unidades","cantidad":4},{"motivo":"NO SE CARGÓ","cantidad":3},{"motivo":"SIN DINERO","cantidad":2},{"motivo":"Error de Armado: Producto roto o mal estado","cantidad":2},{"motivo":"NO ENTREGADO","cantidad":1},{"motivo":"SIN STOCK","cantidad":1}];
window.__TP_DATA__.feriados = ["2026-01-01","2026-05-01","2026-07-09","2026-09-28","2026-12-25"];
window.__TP_DATA__.motivosPorFletero = {"Alejandro Fabian Maiorano":[{"motivo":"CERRADO","cantidad":1}],"Algañaraz German Marcelo":[{"motivo":"CERRADO","cantidad":1}],"Diego Andrés Martorello":[{"motivo":"RECHAZO","cantidad":1},{"motivo":"NO ENTREGADO","cantidad":1},{"motivo":"CERRADO","cantidad":1}],"Emanuel Valentino Cossu":[{"motivo":"SIN DINERO","cantidad":1},{"motivo":"CERRADO","cantidad":1}],"Ezequiel Dario Gargan":[{"motivo":"CERRADO","cantidad":2}],"Leandro Martín Cossu":[{"motivo":"RECHAZO","cantidad":3}],"Leo Damian Moncada":[{"motivo":"RECHAZO","cantidad":1}],"Marcelo Javier Acuña":[{"motivo":"NO SE CARGÓ","cantidad":1}],"Rodrigo Martin Soto":[{"motivo":"RECHAZO","cantidad":1},{"motivo":"SIN DINERO","cantidad":1}]};
window.__TP_DATA__.estadisticasFletero = {"Alejandro Fabian Maiorano":{"recTot":1,"recBol":1,"prodSuel":0,"itemsRech":4,"impRech":76396,"repartos":4,"cliSac":90,"cliEnt":89,"compSac":138,"compEnt":137},"Algañaraz German Marcelo":{"recTot":1,"recBol":1,"prodSuel":0,"itemsRech":60,"impRech":90967,"repartos":5,"cliSac":140,"cliEnt":139,"compSac":204,"compEnt":203},"Diego Andrés Martorello":{"recTot":2,"recBol":3,"prodSuel":0,"itemsRech":20,"impRech":52612,"repartos":7,"cliSac":140,"cliEnt":138,"compSac":247,"compEnt":244},"Edgardo Jacinto Gomez":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":4,"impRech":63330,"repartos":6,"cliSac":127,"cliEnt":127,"compSac":180,"compEnt":180},"Emanuel Valentino Cossu":{"recTot":2,"recBol":2,"prodSuel":0,"itemsRech":154,"impRech":377170,"repartos":5,"cliSac":118,"cliEnt":116,"compSac":181,"compEnt":179},"Enzo Julián Rizzoni":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":0,"impRech":0,"repartos":2,"cliSac":50,"cliEnt":50,"compSac":83,"compEnt":83},"Ezequiel Dario Gargan":{"recTot":1,"recBol":2,"prodSuel":0,"itemsRech":62,"impRech":162628,"repartos":2,"cliSac":63,"cliEnt":62,"compSac":111,"compEnt":109},"Leandro Martín Cossu":{"recTot":2,"recBol":3,"prodSuel":0,"itemsRech":4,"impRech":22962,"repartos":5,"cliSac":107,"cliEnt":105,"compSac":145,"compEnt":142},"Leo Damian Moncada":{"recTot":0,"recBol":1,"prodSuel":0,"itemsRech":27,"impRech":51486,"repartos":5,"cliSac":110,"cliEnt":110,"compSac":155,"compEnt":154},"Marcelo Javier Acuña":{"recTot":0,"recBol":1,"prodSuel":0,"itemsRech":6,"impRech":7781,"repartos":5,"cliSac":103,"cliEnt":103,"compSac":150,"compEnt":149},"Mario Luis Gastiarena":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":0,"impRech":0,"repartos":4,"cliSac":120,"cliEnt":120,"compSac":172,"compEnt":172},"Rodrigo Martin Soto":{"recTot":2,"recBol":2,"prodSuel":0,"itemsRech":143,"impRech":662415,"repartos":4,"cliSac":91,"cliEnt":89,"compSac":141,"compEnt":139}};
window.__TP_DATA__.analisisRechazos = {"importe":1567748,"facturado":174247142,"zonas":[{"nombre":"MAR DEL PLATA","pct":1.1,"rech":16,"sac":1482}],"vendedores":[{"nombre":"Melanie Larrama","pct":2.1,"rech":3,"sac":143},{"nombre":"Julian Nuñez","pct":1.7,"rech":3,"sac":175},{"nombre":"Ludmila Aylen Martinez","pct":1.5,"rech":3,"sac":196},{"nombre":"Lucas Giayetto","pct":1.2,"rech":2,"sac":169},{"nombre":"Matias Parada","pct":0.8,"rech":1,"sac":128},{"nombre":"Ezequiel Hack","pct":0.7,"rech":1,"sac":140},{"nombre":"Maria Noelia Madia","pct":0.6,"rech":1,"sac":155},{"nombre":"Nicolas Martinez","pct":0.6,"rech":1,"sac":172}],"clientes":[{"nombre":"ALEJANDRO RAUL CACCIUTTO","loc":"MAR DEL PLATA","cantidad":2},{"nombre":"NICOLAS LIBONATI","loc":"MAR DEL PLATA","cantidad":2},{"nombre":"MARCELA ALVAREZ","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"MARIA ALEJANDRA GONZALEZ","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"DISTRIBUIDORA CACHITA DINEGO S.A","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"CAI XIAOQING","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"IBAÑEZ RICARDO DARIO","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"MARIA BELEN ANTONUCCI","loc":"MAR DEL PLATA","cantidad":1}],"proveedores":[{"nombre":"Pepsico de Argentina SRL","pct":99.5},{"nombre":"GEORGALOS HNOS S A I C A","pct":97.9},{"nombre":"SOFTYS ARGENTINA S.A.","pct":99.2},{"nombre":"PILAGA S.A.","pct":97.3},{"nombre":"ENTRENUTS SRL","pct":96.4}]};
window.__TP_DATA__.proveedoresPorFletero = {"Alejandro Fabian Maiorano":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":99.5},{"prov":"SOFTYS ARGENTINA S.A.","pct":96.1},{"prov":"PILAGA S.A.","pct":100}],"Algañaraz German Marcelo":[{"prov":"Pepsico de Argentina SRL","pct":99.7},{"prov":"GEORGALOS HNOS S A I C A","pct":99.7},{"prov":"SOFTYS ARGENTINA S.A.","pct":97.2},{"prov":"LAGOPUELO S.A.","pct":100},{"prov":"PILAGA S.A.","pct":100}],"Diego Andrés Martorello":[{"prov":"Pepsico de Argentina SRL","pct":99.8},{"prov":"GEORGALOS HNOS S A I C A","pct":98.8},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"PILAGA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":100}],"Edgardo Jacinto Gomez":[{"prov":"Pepsico de Argentina SRL","pct":99.6},{"prov":"GEORGALOS HNOS S A I C A","pct":99.8},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"PILAGA S.A.","pct":100},{"prov":"COMPAÑIA DE ALIMENTOS FARGO SA","pct":100}],"Emanuel Valentino Cossu":[{"prov":"Pepsico de Argentina SRL","pct":98},{"prov":"SOFTYS ARGENTINA S.A.","pct":99.6},{"prov":"GEORGALOS HNOS S A I C A","pct":98.6},{"prov":"PILAGA S.A.","pct":92.7},{"prov":"ENTRENUTS SRL","pct":100}],"Enzo Julián Rizzoni":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100}],"Ezequiel Dario Gargan":[{"prov":"Pepsico de Argentina SRL","pct":99.7},{"prov":"GEORGALOS HNOS S A I C A","pct":96.1},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":95.9},{"prov":"PILAGA S.A.","pct":82.6}],"Leandro Martín Cossu":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":99.7},{"prov":"SOFTYS ARGENTINA S.A.","pct":96.9},{"prov":"PILAGA S.A.","pct":100}],"Leo Damian Moncada":[{"prov":"Pepsico de Argentina SRL","pct":99.5},{"prov":"GEORGALOS HNOS S A I C A","pct":99.5},{"prov":"SOFTYS ARGENTINA S.A.","pct":100}],"Marcelo Javier Acuña":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":99.4},{"prov":"ENTRENUTS SRL","pct":97.9},{"prov":"PILAGA S.A.","pct":100}],"Mario Luis Gastiarena":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"PILAGA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":100}],"Rodrigo Martin Soto":[{"prov":"Pepsico de Argentina SRL","pct":97.9},{"prov":"GEORGALOS HNOS S A I C A","pct":77.1},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"COMPAÑIA DE ALIMENTOS FARGO SA","pct":92.3},{"prov":"PILAGA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":77.8}]};
window.__TP_DATA__.mesAnterior = {"clave":"2026-09","anio":2026,"mes":9,"efGeneral":96.5,"cartonGeneral":66.5,"repartos":268,"boletasEnt":9188,"boletasSac":9415,"clientesEnt":6702,"clientesSac":6798,"plataRech":18230306,"premiosTotal":0,"fleteros":12,"ranking":[{"nombre":"Marcelo Javier Acuña","repartos":15,"asist":68,"efE":98.6,"efC":62,"premio":0},{"nombre":"Edgardo Jacinto Gomez","repartos":27,"asist":100,"efE":98.5,"efC":76.2,"premio":0},{"nombre":"Mario Luis Gastiarena","repartos":22,"asist":100,"efE":98.2,"efC":55.5,"premio":0},{"nombre":"Leo Damian Moncada","repartos":21,"asist":95,"efE":98,"efC":63.1,"premio":0},{"nombre":"Enzo Julián Rizzoni","repartos":29,"asist":100,"efE":97.7,"efC":56.8,"premio":0},{"nombre":"Algañaraz German Marcelo","repartos":12,"asist":55,"efE":97.1,"efC":53.5,"premio":0},{"nombre":"Ezequiel Dario Gargan","repartos":19,"asist":86,"efE":96.5,"efC":68.6,"premio":0},{"nombre":"Diego Andrés Martorello","repartos":35,"asist":100,"efE":96.1,"efC":69.4,"premio":0},{"nombre":"Rodrigo Martin Soto","repartos":22,"asist":100,"efE":95.8,"efC":71.6,"premio":0},{"nombre":"Emanuel Valentino Cossu","repartos":22,"asist":100,"efE":94.8,"efC":80.2,"premio":0},{"nombre":"Leandro Martín Cossu","repartos":22,"asist":100,"efE":94.1,"efC":59.9,"premio":0},{"nombre":"Alejandro Fabian Maiorano","repartos":22,"asist":100,"efE":93.6,"efC":65.5,"premio":0}]};
