/* GENERADO AUTOMATICAMENTE por robot-nube.ps1 (API Gescom, GitHub Actions) - NO EDITAR A MANO
   Ultima actualizacion: 2026-10-05 07:39 */
window.__TP_CONFIG__ = { SHEET_CSV_URL: '', umbrales: { bueno: 90, medio: 75 }, diasHistorial: 14 };
window.__TP_DATA__ = { registros: [
 {"fecha":"2026-10-01","fletero":"Alejandro Fabian Maiorano","zona":"","repartos":1,"entregas_asignadas":29,"entregas_realizadas":26,"cartones_a_retornar":33,"cartones_retornados":29}
,{"fecha":"2026-10-01","fletero":"Algañaraz German Marcelo","zona":"","repartos":1,"entregas_asignadas":49,"entregas_realizadas":49,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-01","fletero":"Diego Andrés Martorello","zona":"","repartos":2,"entregas_asignadas":66,"entregas_realizadas":66,"cartones_a_retornar":60,"cartones_retornados":56}
,{"fecha":"2026-10-01","fletero":"Edgardo Jacinto Gomez","zona":"","repartos":1,"entregas_asignadas":42,"entregas_realizadas":39,"cartones_a_retornar":29,"cartones_retornados":29}
,{"fecha":"2026-10-01","fletero":"Emanuel Valentino Cossu","zona":"","repartos":1,"entregas_asignadas":39,"entregas_realizadas":37,"cartones_a_retornar":29,"cartones_retornados":27}
,{"fecha":"2026-10-01","fletero":"Ezequiel Dario Gargan","zona":"","repartos":1,"entregas_asignadas":55,"entregas_realizadas":51,"cartones_a_retornar":34,"cartones_retornados":34}
,{"fecha":"2026-10-01","fletero":"Leandro Martín Cossu","zona":"","repartos":1,"entregas_asignadas":23,"entregas_realizadas":23,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-01","fletero":"Leo Damian Moncada","zona":"","repartos":1,"entregas_asignadas":33,"entregas_realizadas":32,"cartones_a_retornar":36,"cartones_retornados":0}
,{"fecha":"2026-10-01","fletero":"Marcelo Javier Acuña","zona":"","repartos":1,"entregas_asignadas":39,"entregas_realizadas":38,"cartones_a_retornar":36,"cartones_retornados":34}
,{"fecha":"2026-10-01","fletero":"Mario Luis Gastiarena","zona":"","repartos":1,"entregas_asignadas":36,"entregas_realizadas":36,"cartones_a_retornar":42,"cartones_retornados":40}
,{"fecha":"2026-10-01","fletero":"Rodrigo Martin Soto","zona":"","repartos":1,"entregas_asignadas":33,"entregas_realizadas":32,"cartones_a_retornar":40,"cartones_retornados":30}
,{"fecha":"2026-10-02","fletero":"Alejandro Fabian Maiorano","zona":"","repartos":2,"entregas_asignadas":71,"entregas_realizadas":71,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Algañaraz German Marcelo","zona":"","repartos":2,"entregas_asignadas":82,"entregas_realizadas":82,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Diego Andrés Martorello","zona":"","repartos":3,"entregas_asignadas":123,"entregas_realizadas":123,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Edgardo Jacinto Gomez","zona":"","repartos":2,"entregas_asignadas":60,"entregas_realizadas":60,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Emanuel Valentino Cossu","zona":"","repartos":2,"entregas_asignadas":102,"entregas_realizadas":102,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Enzo Julián Rizzoni","zona":"","repartos":2,"entregas_asignadas":80,"entregas_realizadas":80,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Leandro Martín Cossu","zona":"","repartos":2,"entregas_asignadas":78,"entregas_realizadas":78,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Leo Damian Moncada","zona":"","repartos":2,"entregas_asignadas":69,"entregas_realizadas":69,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Marcelo Javier Acuña","zona":"","repartos":2,"entregas_asignadas":71,"entregas_realizadas":71,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Mario Luis Gastiarena","zona":"","repartos":2,"entregas_asignadas":92,"entregas_realizadas":92,"cartones_a_retornar":0,"cartones_retornados":0}
,{"fecha":"2026-10-02","fletero":"Rodrigo Martin Soto","zona":"","repartos":2,"entregas_asignadas":65,"entregas_realizadas":65,"cartones_a_retornar":0,"cartones_retornados":0}
] };
window.__TP_DATA__.motivos = [{"motivo":"RECHAZO","cantidad":5},{"motivo":"CERRADO","cantidad":3},{"motivo":"Error de Armado: Diferencia de unidades","cantidad":3},{"motivo":"ERROR DE PREVENTA","cantidad":2},{"motivo":"NO SE CARGÓ","cantidad":2},{"motivo":"Error de Armado: Producto roto o mal estado","cantidad":1},{"motivo":"SIN STOCK","cantidad":1}];
window.__TP_DATA__.feriados = ["2026-01-01","2026-05-01","2026-07-09","2026-09-28","2026-12-25"];
window.__TP_DATA__.motivosPorFletero = {"Alejandro Fabian Maiorano":[{"motivo":"CERRADO","cantidad":1}],"Ezequiel Dario Gargan":[{"motivo":"CERRADO","cantidad":2}],"Marcelo Javier Acuña":[{"motivo":"NO SE CARGÓ","cantidad":1}]};
window.__TP_DATA__.estadisticasFletero = {"Alejandro Fabian Maiorano":{"recTot":1,"recBol":1,"prodSuel":0,"itemsRech":4,"impRech":76396,"repartos":3,"cliSac":58,"cliEnt":57,"compSac":85,"compEnt":84},"Algañaraz German Marcelo":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":0,"impRech":0,"repartos":3,"cliSac":77,"cliEnt":77,"compSac":113,"compEnt":113},"Diego Andrés Martorello":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":0,"impRech":0,"repartos":5,"cliSac":96,"cliEnt":96,"compSac":156,"compEnt":156},"Edgardo Jacinto Gomez":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":4,"impRech":63330,"repartos":3,"cliSac":55,"cliEnt":55,"compSac":86,"compEnt":86},"Emanuel Valentino Cossu":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":29,"impRech":70771,"repartos":3,"cliSac":70,"cliEnt":70,"compSac":101,"compEnt":101},"Enzo Julián Rizzoni":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":0,"impRech":0,"repartos":2,"cliSac":39,"cliEnt":39,"compSac":63,"compEnt":63},"Ezequiel Dario Gargan":{"recTot":1,"recBol":2,"prodSuel":0,"itemsRech":62,"impRech":162628,"repartos":1,"cliSac":30,"cliEnt":29,"compSac":55,"compEnt":53},"Leandro Martín Cossu":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":0,"impRech":0,"repartos":3,"cliSac":63,"cliEnt":63,"compSac":87,"compEnt":87},"Leo Damian Moncada":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":4,"impRech":4486,"repartos":3,"cliSac":62,"cliEnt":62,"compSac":86,"compEnt":86},"Marcelo Javier Acuña":{"recTot":0,"recBol":1,"prodSuel":0,"itemsRech":6,"impRech":7781,"repartos":3,"cliSac":63,"cliEnt":63,"compSac":98,"compEnt":97},"Mario Luis Gastiarena":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":0,"impRech":0,"repartos":3,"cliSac":80,"cliEnt":80,"compSac":105,"compEnt":105},"Rodrigo Martin Soto":{"recTot":0,"recBol":0,"prodSuel":0,"itemsRech":21,"impRech":48411,"repartos":3,"cliSac":55,"cliEnt":55,"compSac":82,"compEnt":82}};
window.__TP_DATA__.analisisRechazos = {"importe":433804,"facturado":104764243,"zonas":[{"nombre":"MAR DEL PLATA","pct":0.5,"rech":4,"sac":874}],"vendedores":[{"nombre":"Ludmila Aylen Martinez","pct":1.7,"rech":2,"sac":120},{"nombre":"Matias Parada","pct":1.3,"rech":1,"sac":76},{"nombre":"Nicolas Martinez","pct":1,"rech":1,"sac":103}],"clientes":[{"nombre":"ALEJANDRO RAUL CACCIUTTO","loc":"MAR DEL PLATA","cantidad":2},{"nombre":"NICOLAS LIBONATI","loc":"MAR DEL PLATA","cantidad":2},{"nombre":"LI MEIFANG","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"NAZARENO DARIO FABIAN RAMIREZ","loc":"SANTA CLARA DEL MAR","cantidad":1},{"nombre":"SAN ALBERTO BALCARCE S R L","loc":"BALCARCE","cantidad":1},{"nombre":"MARIA ALEJANDRA GONZALEZ","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"NI JINMU","loc":"MAR DEL PLATA","cantidad":1},{"nombre":"MARIA AMALIA PAGLIONE","loc":"BALCARCE","cantidad":1}],"proveedores":[{"nombre":"Pepsico de Argentina SRL","pct":99.8},{"nombre":"GEORGALOS HNOS S A I C A","pct":99.4},{"nombre":"SOFTYS ARGENTINA S.A.","pct":99.3},{"nombre":"PILAGA S.A.","pct":98}]};
window.__TP_DATA__.proveedoresPorFletero = {"Alejandro Fabian Maiorano":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":99.1},{"prov":"SOFTYS ARGENTINA S.A.","pct":89.5}],"Algañaraz German Marcelo":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"PILAGA S.A.","pct":100}],"Diego Andrés Martorello":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"PILAGA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":100}],"Edgardo Jacinto Gomez":[{"prov":"GEORGALOS HNOS S A I C A","pct":99.8},{"prov":"Pepsico de Argentina SRL","pct":98.8},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"PILAGA S.A.","pct":100},{"prov":"COMPAÑIA DE ALIMENTOS FARGO SA","pct":100}],"Emanuel Valentino Cossu":[{"prov":"Pepsico de Argentina SRL","pct":99.2},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"PILAGA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":100}],"Enzo Julián Rizzoni":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100}],"Ezequiel Dario Gargan":[{"prov":"Pepsico de Argentina SRL","pct":99.4},{"prov":"GEORGALOS HNOS S A I C A","pct":92.2},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":94.3},{"prov":"PILAGA S.A.","pct":66.6}],"Leandro Martín Cossu":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100}],"Leo Damian Moncada":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":99.1}],"Marcelo Javier Acuña":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":99.3},{"prov":"PILAGA S.A.","pct":100},{"prov":"ENTRENUTS SRL","pct":97.7}],"Mario Luis Gastiarena":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"PILAGA S.A.","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100}],"Rodrigo Martin Soto":[{"prov":"Pepsico de Argentina SRL","pct":100},{"prov":"GEORGALOS HNOS S A I C A","pct":100},{"prov":"SOFTYS ARGENTINA S.A.","pct":100},{"prov":"COMPAÑIA DE ALIMENTOS FARGO SA","pct":91},{"prov":"PILAGA S.A.","pct":100}]};
window.__TP_DATA__.mesAnterior = {"clave":"2026-09","anio":2026,"mes":9,"efGeneral":96.5,"cartonGeneral":66.5,"repartos":268,"boletasEnt":9188,"boletasSac":9415,"clientesEnt":6702,"clientesSac":6798,"plataRech":18230306,"premiosTotal":0,"fleteros":12,"ranking":[{"nombre":"Marcelo Javier Acuña","repartos":15,"asist":68,"efE":98.6,"efC":62,"premio":0},{"nombre":"Edgardo Jacinto Gomez","repartos":27,"asist":100,"efE":98.5,"efC":76.2,"premio":0},{"nombre":"Mario Luis Gastiarena","repartos":22,"asist":100,"efE":98.2,"efC":55.5,"premio":0},{"nombre":"Leo Damian Moncada","repartos":21,"asist":95,"efE":98,"efC":63.1,"premio":0},{"nombre":"Enzo Julián Rizzoni","repartos":29,"asist":100,"efE":97.7,"efC":56.8,"premio":0},{"nombre":"Algañaraz German Marcelo","repartos":12,"asist":55,"efE":97.1,"efC":53.5,"premio":0},{"nombre":"Ezequiel Dario Gargan","repartos":19,"asist":86,"efE":96.5,"efC":68.6,"premio":0},{"nombre":"Diego Andrés Martorello","repartos":35,"asist":100,"efE":96.1,"efC":69.4,"premio":0},{"nombre":"Rodrigo Martin Soto","repartos":22,"asist":100,"efE":95.8,"efC":71.6,"premio":0},{"nombre":"Emanuel Valentino Cossu","repartos":22,"asist":100,"efE":94.8,"efC":80.2,"premio":0},{"nombre":"Leandro Martín Cossu","repartos":22,"asist":100,"efE":94.1,"efC":59.9,"premio":0},{"nombre":"Alejandro Fabian Maiorano","repartos":22,"asist":100,"efE":93.6,"efC":65.5,"premio":0}]};
